name: .NET Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x" # Adjust the version as needed
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
      - name: Run dotnet format check
        run: dotnet format --check
        env:
          PATH: ${{ github.env.PATH }}:/home/runner/.dotnet/tools
